import time
import keyboard
from selenium import webdriver
account_id = input("enter the insta account you wanna send message to : ")
message = input("enter the message you wanna send to the person: ")
my_id = input("enter any proxy insta account : ")
my_pwd = input("enter password of the proxy accoun: ")
browser = webdriver.Chrome()
browser.get("https://www.instagram.com/accounts/login/")
browser.maximize_window()
time.sleep(2)
browser.find_element_by_name("username").send_keys(my_id)
browser.find_element_by_name("password").send_keys(my_pwd)
keyboard.press_and_release("enter")
keyboard.press_and_release("enter")
time.sleep(4)
browser.find_element_by_xpath("/html/body/div[1]/section/nav/div[2]/div/div/div[2]/input").send_keys(account_id)
time.sleep(4)
id_choice = browser.find_element_by_class_name("HVWg4                 ")
id_choice.click()
time.sleep(2)
message_profile_button = browser.find_element_by_class_name('_8A5w5    ')
message_profile_button.click()
time.sleep(2)
notnowb = browser.find_element_by_class_name('HoLwm ')
notnowb.click()
time.sleep(1)
message_button = browser.find_element_by_xpath("/html/body/div[1]/section/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div/div[2]/textarea")
message_button.send_keys(message)
time.sleep(0.5)
keyboard.press_and_release("enter")